apiVersion: v1
kind: Service
metadata:
  name: express-hello
  labels:
    app: express-hello
spec:
  type: ClusterIP
  selector:
    app: express-hello
  ports:
    - name: http
      port: 80
      targetPort: 8080


