name: Build and Push Docker Image

on:
  push:
    branches:
     - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: mohamedf0
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: quay.io/mohamedf0/gh-actions-sample:from-docker

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure Kubernetes access
        run: |
          kubectl config set-cluster target --server="$KUBE_API_URL" --insecure-skip-tls-verify=true
          kubectl config set-credentials gh-actions --token="$KUBE_TOKEN"
          kubectl config set-context target --cluster=target --user=gh-actions
          kubectl config use-context target
        env:
          KUBE_API_URL: ${{ secrets.K8S_API_URL }}
          KUBE_TOKEN: ${{ secrets.K8S_TOKEN }}

      - name: Update deployment image
        run: kubectl rollout restart deployment/express-hello --namespace mo-sandbox

